name: Generate Pull Request Bundle Stats

on: pull_request

jobs:
  stats:
    name: PR Stats
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v2
        with:
          path: pr-branch
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Checkout base
        uses: actions/checkout@v2
        with:
          path: base-branch
          ref: ${{github.base_ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Compare sizes
        uses: typeofweb/typeofweb-bundlephobia-pr-stats-action@pkg
        with:
          pr_directory_name: pr-branch
          base_directory_name: base-branch
        env:
          COMPRESS_BUNDLES: true
